stages:
  - test

image: garfieldius/typo3-ci:php7.2-node12

variables:
  COMPOSER_CACHE_DIR: $CI_PROJECT_DIR/.cache/composer

cache:
  key: "$CI_PROJECT_ID-$CI_COMMIT_REF_NAME-$CI_JOB_NAME"
  paths:
    - $CI_PROJECT_DIR/.cache

lint:
  stage: test
  script:
    - composer install --ansi -n --no-suggest --no-progress
    - bin/php-cs-fixer fix --config=.php_cs --diff -vvv --dry-run

.test: &TEST
  stage: test
  script:
    - rm -rf composer.lock vendor bin
    - composer require --ignore-platform-reqs --ansi -n --no-suggest --no-progress $TYPO3_VERSION
    - ./bin/phpunit -c phpunit.xml

test-7:
  <<: *TEST
  variables:
    TYPO3_VERSION: typo3/cms:^7

test-8:
  <<: *TEST
  variables:
    TYPO3_VERSION: typo3/cms-fluid:^8 typo3/cms-frontend:^8

test-9:
  <<: *TEST
  variables:
    TYPO3_VERSION: typo3/cms-fluid:^9 typo3/cms-frontend:^9

test-10:
  <<: *TEST
  variables:
    TYPO3_VERSION: typo3/cms-fluid:^10 typo3/cms-frontend:^10
