name: 'Test & Lint'

on: [push, pull_request]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: 7.2

      - name: Lint code
        run: |
          composer install --no-scripts --no-plugins --ignore-platform-reqs --no-progress -n --ansi --no-suggest
          bin/php-cs-fixer fix --config=.php_cs --diff --dry-run

  test:
    name: Testing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        typo3:
          - 'typo3/cms:^7'
          - 'typo3/cms-core:^8 typo3/cms-extbase:^8 typo3/cms-fluid:^8'
          - 'typo3/cms-core:^9 typo3/cms-extbase:^9 typo3/cms-fluid:^9'
          - 'typo3/cms-core:^10 typo3/cms-extbase:^10 typo3/cms-fluid:^10'
        php:
          - 7.2
          - 7.3
          - 7.4
        exclude:
          - typo3: 'typo3/cms:^7'
            php: 7.3
          - typo3: 'typo3/cms:^7'
            php: 7.4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Test TYPO3
        run: |
          rm -rf composer.lock vendor bin
          composer require ${{ matrix.typo3 }} --ignore-platform-reqs --no-plugins --no-scripts --no-suggest -n --ansi
          php bin/phpunit -c phpunit.xml
