name: 'Test & Lint'

on: [push, pull_request]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: 7.2

      - name: Lint code
        run: |
          composer install --no-scripts --no-plugins --ignore-platform-reqs --no-progress -n --ansi
          bin/php-cs-fixer fix --config=.php_cs --diff --dry-run --diff-format=udiff

  test:
    name: Testing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
        typo3:
          - '9.5'
          - '10.4'
          - '11.5'
        exclude:
          - php: '7.2'
            typo3: '11.5'
          - php: '7.3'
            typo3: '11.5'
          - php: '8.0'
            typo3: '9.5'
          - php: '8.0'
            typo3: '10.4'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Test TYPO3 ${{ matrix.typo3 }}
        run: |
          jq 'del(.require)' composer.json | jq 'del(.["require-dev"])' > c.json
          rm -rf composer.lock vendor bin typo3_src typo3 index.php composer.json
          mv c.json composer.json
          composer require --ansi -n --no-progress --no-plugins --no-scripts typo3/cms-core:^${{ matrix.typo3 }} typo3/cms-extbase:^${{ matrix.typo3 }} typo3/cms-fluid:^${{ matrix.typo3 }} typo3/cms-frontend:^${{ matrix.typo3 }}
          composer require --dev --ansi -n --no-progress --no-plugins --no-scripts phpunit/phpunit
          php bin/phpunit -c phpunit.xml
