name: 'Code Style'

on: [push, pull_request]

jobs:
  lint:
    name: Code Style Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: 7.4

      - name: Lint code
        run: |
          composer install --no-scripts --no-plugins --ignore-platform-reqs --no-progress -n --ansi
          bin/php-cs-fixer fix --config=.php-cs-fixer.php --diff --dry-run
